BAU - Deprecate scheme builder
Description:
- Dependabot PRs are failing because the latest version of `controller-runtime` has deprecated `scheme.Builder` (https://github.com/alphagov/govuk-job-request-operator/actions/runs/26217422184/job/77143291873?pr=6)
```
Error: api/v1/groupversion_info.go:36:19: SA1019: scheme.Builder is deprecated: This helper is only useful in api packages, but api packages should be easy to import and hence have minimal dependencies. Typically, these dependencies include only the standard library, k8s.io/apimachinery and other api packages. (staticcheck)
```
- https://github.com/kubernetes-sigs/controller-runtime/pull/3461 was used to make the changes